# This is the config file for the VR playback of the point clouds
# Note: After launching CubePlugin, the "LevelWithCharacter" level
# must be loaded

[Loading]

# The path to the folder containing the simulation data
data_path = "C:\\Users\\its\\Documents\\Unreal Projects\\CubePlugin 5.3\\Data"
# data_path = "C:\\Users\\its\\Documents\\Unreal Projects\\CubePlugin 5.3\\Chippendale"

# The name of the odometry file
odometry_name = "Odometry5.csv"
# odometry_name = "Odometry2.csv'

# The name of the global point cloud
global_name = "Global Point Cloud.las"

# The name of the folder containing the local point clouds
local_name = "Local Point Clouds"

# The name of the folder containing the images
image_name = "Images"

# If load_one is set to true, this is the single point cloud that is loaded
single_name = "Local Point Clouds\\1688451456.986476606.las"

# Correction angle for the global map PITCH in degrees
pitch_correction = 0.00

# Correction angle for the global map YAW in degrees
yaw_correction = 0.00

# Correction angle for the global map ROLL in degrees
roll_correction = -0.29

[VR_Parameters]

# The number of TOTAL imported frames
number_frames = 30

# The height that the bird's eye view is set to this
# The units must be in CENTIMETRES
# Typical values are 5000-20000 cm
height_birds = 10000.0

# Import at a rate of 1 per import_every frames
import_every = 1

# Playback at this times the realtime speed
playback_speed = 0.05

# Display points at these sizes when in road or bird's eye view
local_ground_size = 0.5
# local_ground_size = 1.0
local_bird_size = 0.5
global_ground_size = 0.05
global_bird_size = 0.1

# Whether photos are imported for the video playback
# This must be set to false if there are no images available
photo_import = false

# Set the camera exposure (lower value means brighter)
exposure = 0.1
# exposure = 0.6

# Whether we wish to load a global map
load_global = true

# Mode for whether we want to load just a single point cloud
# If true, load_global and photo_import must both be set to false
load_one = false

