# This is the config file for the VR playback of the point clouds
# Note: After launching CubePlugin, the "LevelWithCharacter" level
# must be loaded

[Loading]

# The path to the folder containing the simulation data
data_path = "C:\\Users\\its\\Documents\\Unreal Projects\\CubePlugin\\Data"
# data_path = "C:\\Users\\its\\Documents\\Unreal Projects\\CubePlugin\\Chippendale"

# The name of the odometry file
odometry_name = "Odometry.csv"

# The name of the global point cloud
global_name = "Global Point Cloud.las"

# The name of the folder containing the local point clouds
local_name = "Local Point Clouds"

# The name of the folder containing the images
image_name = "Images"

[VR_Parameters]

# The number of TOTAL imported frames
number_frames = 300

# The height that the bird's eye view is set to this
# The units must be in CENTIMETRES
# Typical values are 5000-20000 cm
height_birds = 10000.0

# Import at a rate of 1 per import_every frames
import_every = 1

# Playback at this times the realtime speed
playback_speed = 0.5

# Display points at these sizes when in road or bird's eye view
local_ground_size = 0.5
local_bird_size = 0.5
global_ground_size = 0.05
global_bird_size = 0.1

# Whether photos are imported for the video playback
# This must be set to false if there are no images available
photo_import = false



